server:
  port: 7007
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:gabriel.gutierrezq@vallegrande.edu.pe}
    password: ${MAIL_PASSWORD:racr rffo bvmu szay}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
